version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:5001"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongodb
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "${USER_SERVICE_PORT}:5002"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongodb
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:5000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - user-service
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - api-gateway
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge